services:
  nginx:
    image: 'nginx'
    container_name: nginx
    ports:
      - '80:80'
    environment:
      discovery.type: single-node
    volumes:
      - .\nginx.conf:/etc/nginx/conf.d/default.conf
  web1:
    image: 'mcr.microsoft.com/dotnet/samples:aspnetapp'
    container_name: frontend
    ports:
      - '8001:80'
    volumes:
      - .\site.js:/app/wwwroot/js/site.js  
  web2:
    image: 'mcr.microsoft.com/dotnet/samples:aspnetapp'
    container_name: api
    ports:
      - '8002:80'