services:
  nginx:
    image: 'nginx'
    container_name: nginx
    ports:
      - '8000:8000'
    environment:
      discovery.type: single-node
    volumes:
      - .\nginx.conf:/etc/nginx/conf.d/default.conf
  web1:
    image: 'mcr.microsoft.com/dotnet/samples:aspnetapp'
    container_name: web1
    ports:
      - '8001:80'
  web2:
    image: 'mcr.microsoft.com/dotnet/samples:aspnetapp'
    container_name: web2
    ports:
      - '8002:80'
